[Inputs]
data_dir = /Users/andy/projects/Astro_Neo/input_files/astronomy_test/
data_file = left_pha_grp.fits
bg_file = left_mbg.fits
rsp_file = left_rmf.fits
output_file =  result/GA_test_500.csv

[Populations]
population = 25
num_gen = 10
best_sample = 10
lucky_few = 10
CR = 0.7

[Mutations]
chance_of_mutation = 10
original_chance_of_mutation = 10
# 3 = DE
F = 0.5
mutated_options = 1

[Paths]
npaths = 1
center =8.422
# center =8.422,9.169
# fits=EmissionLorentz,EmissionLorentz
# fits=Sherpa_APEC
fits=XspecSpectrum

[Outputs]
print_graph = False
num_output_paths = True
steady_state_exit = True
distributed = 1
profile = False
