[Inputs]
data_dir = /Users/andy/projects/Astro_Neo/input_files/astronomy_test/
data_file = left_pha_grp.fits
bg_file = left_mbg.fits
rsp_file = left_rmf.fits
output_file = result/Astromony/Test.csv
fits_file = input_files/astronomy_test/left_pha_grp.fits

[Populations]
population = 1000
num_gen= 25
best_sample = 20
lucky_few = 10

[Mutations]
chance_of_mutation = 20
original_chance_of_mutation = 20
mutated_options = 0

[Paths]
npaths = 1
fits = Thermal
center = 0
corr = False
# corr_paths = 1,0,3,4
corr_paths = 0

[Outputs]
print_graph = False
num_output_paths = False
